### ISSUE TITLE
I can't make a build

### ISSUE THREAD

**Issue by SHCDevelops** [MechTechnology/SmartStitch#24]
I wanted to make some improvements, but I can't build the application according to the ready-made build.spec file

https://github.com/MechTechnology/SmartStitch/assets/121876687/18247682-a0f4-4ddf-a19d-88e686fc8394

**Comment by SHCDevelops** [comment]
And I would like to add, I know setup.py ended with an error, so I installed all the packages manually and I still get an error like:
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 200, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pkg_resources\__init__.py", line 35, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "plistlib.py", line 70, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "xml\parsers\expat.py", line 4, in <module>
ModuleNotFoundError: No module named 'pyexpat'
```

**Comment by SHCDevelops** [comment]
And one more addition, even after downloading all the files from the already finished release, I still get an error:
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 35, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 27, in _pyi_rthook
FileNotFoundError: Tcl data directory "C:\Users\admin\Desktop\SmartStitch\build\Build\tcl" not found.
```

**Comment by AbhiMayadam** [comment]
Just out of curiosity, what version of python are you targeting when you are trying to build? Also just out of curiosity, could you try building from powershell instead of the terminal built into VSC? I don't think that's the reason why but you never know.
